name: Hardhat Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Yarn & Node install cache
        # You may pin to the exact commit or the version.
        # uses: EgorDm/gha-yarn-node-cache@5e3a518810b21a8e0e1d236a3db83a18cfc1be9e
        uses: EgorDm/gha-yarn-node-cache@v1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: forge-test

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Show NodeJS version
        run: npm --version

      - name: Install Dependencies
        run: npm install

      - name: Run hardhat Test
        run: npx hardhat test

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
      - name: Show Python version
        run: python --version

      - name: Install slither
        run: pip3 install slither-analyzer

      - name: Run slither
        run: slither ./src/NFTtoken.sol
